// Generated by CoffeeScript 1.3.3

this.QuoteSlideShow = (function() {

  function QuoteSlideShow(quotes) {
    this.currentQuote = 0;
    this.quotes = $.shuffle(quotes);
    this.quotes.hide().first().show();
    this.totalQuotes = quotes.length;
  }

  QuoteSlideShow.prototype.start = function() {
    var rotation;
    return rotation = setInterval((function(self) {
      return function() {
        return self.showQuote();
      };
    })(this), 5000);
  };

  QuoteSlideShow.prototype.showQuote = function() {
    var _this = this;
    return $(this.quotes[this.currentQuote]).fadeOut(500, function() {
      if (_this.currentQuote >= (_this.quotes.length - 1)) {
        _this.currentQuote = 0;
      } else {
        _this.currentQuote++;
      }
      return $(_this.quotes[_this.currentQuote]).fadeIn(500);
    });
  };

  return QuoteSlideShow;

})();
